"use client";
import { useState } from "react";
import Link from "next/link";
import Icon from "../components/Icon";
import AsyncState from "../components/AsyncState";
import { humanize } from "../lib/propertyPresentation";
import LeadActions from "./LeadActions";
export interface LeadRecord { id: string; motivation_score: number; stack_score: number | null; motivation_type: string | null; likely_bunny: string | null; recommended_structure: string | null; bunny_confidence: string | null; approach: string | null; method: string | null; segment: string | null; status: string; owner_name: string | null; address: string | null; distress: boolean }
export default function LeadsTable({ leads, counts }: { leads: LeadRecord[]; counts: { leads: number; mailed: number; closes: number } }) {
  const [query, setQuery] = useState("");
  const [distressOnly, setDistressOnly] = useState(false);
  const filtered = leads.filter(lead => (!distressOnly || lead.distress) && `${lead.address ?? ""} ${lead.owner_name ?? ""} ${lead.recommended_structure ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page wide"><div className="page-heading"><div><div className="page-eyebrow">Owner research</div><h1>Start a better conversation.</h1><p>Review the evidence behind each lead before preparing outreach. Motivation signals are inferences, not verified intent.</p></div><Link href="/brief" className="btn-primary">Open action brief<Icon name="right" size={14} /></Link></div>
    <div className="leads-intro"><span>Mailable leads<strong>{counts.leads}</strong></span><span>Owners mailed<strong>{counts.mailed}</strong></span><span>Closed deals<strong>{counts.closes}</strong></span><span>Estimated cost per close<strong>{counts.closes ? `$${Math.round(counts.mailed * 1.12 / counts.closes).toLocaleString()}` : "Not available"}</strong></span></div>
    <p className="table-footnote" style={{ padding: "0 0 20px", border: 0 }}>Cost estimate uses $1.12 per mailed lead, not a ledger of actual expenses. Ranking uses the existing composite seller signal score.</p>
    <div className="pipeline-controls"><label className="explorer-search pipeline-search"><Icon name="search" size={15} /><input type="search" aria-label="Search leads" placeholder="Find an owner, address, or structure..." value={query} onChange={event => setQuery(event.target.value)} /></label><div className="filter-strip" style={{ marginTop: 0 }}><button className="filter-pill" aria-pressed={distressOnly} onClick={() => setDistressOnly(!distressOnly)}>Distress signals only</button><span className="table-footnote" style={{ padding: 0, border: 0 }}>{filtered.length} of the top {leads.length} leads</span></div></div>
    {!leads.length ? <div className="panel"><AsyncState title="Your next conversation starts here" description="Generate the lead list from your current property data in the action brief. Only leads that pass the existing mailability gates appear here." action={{ href: "/brief", label: "Open lead generation" }} /></div> : !filtered.length ? <div className="panel"><AsyncState title="No leads match your search" description="Try another owner name or turn off the distress filter." /></div> : <div className="tablewrap"><table className="leads-table"><thead><tr><th>Owner / property</th><th>Seller signals</th><th>Financing hypothesis</th><th>Outreach route</th><th>Score</th><th>Next action</th></tr></thead><tbody>{filtered.map(lead => <tr key={lead.id}><td><strong className="lead-primary">{lead.owner_name ?? "Owner not identified"}</strong><span className="lead-secondary">{lead.address ?? "Address unavailable"}</span><span className="lead-secondary">{humanize(lead.status)}</span></td><td>{humanize(lead.motivation_type ?? lead.segment)}{lead.likely_bunny && lead.likely_bunny !== "none" && <span className="lead-secondary">{humanize(lead.likely_bunny)}</span>}{lead.distress && <span className="screening-label is-review"><Icon name="warning" size={11} />Recorded distress</span>}</td><td>{humanize(lead.recommended_structure)}{lead.bunny_confidence != null && <span className="lead-secondary">Model confidence {Math.round(Number(lead.bunny_confidence) * 100)}%</span>}{lead.recommended_structure === "subject_to" && <span className="lead-secondary" style={{ color: "var(--warn)" }}>Due-on-sale risk. Attorney review.</span>}</td><td>{lead.approach ?? "Not specified"}<span className="lead-secondary">{lead.method ?? ""}</span></td><td><span className="lead-score">{lead.stack_score ?? lead.motivation_score}</span></td><td><LeadActions leadId={lead.id} label={lead.address ?? lead.owner_name ?? undefined} /></td></tr>)}</tbody></table></div>}
  </div>;
}
