/**
 * Dossier generator (SHOW layer) — turns the engine outputs into the cited, ranked
 * markdown dossier that examples/dossier-1301-wertland.md was hand-run as. This is the
 * product's actual deliverable; the deal modal / export consume it.
 */
import type { ScoreResult } from "../scoring/score.js";
import type { SensitivityResult } from "../scoring/sensitivity.js";
import type { FinancingResult, Offer } from "../financing/recommend.js";

export interface DossierDepth {
  sensitivity?: SensitivityResult;
  gates?: { passed: boolean; failures: string[] };
  dataConfidence?: number;
  rentFloor?: { hudFmrMonthly: number | null; belowFloor: boolean; fmrYear: number | null; cbsaName: string | null };
}

export interface DossierFacts {
  address: string;
  apn: string;
  gpin?: string;
  zoneCode: string | null;
  byRoomLegal: boolean | null;
  stabilityFlag?: string | null;
  assessedValue: number | null;
  beds: number | null;
  ownerName?: string | null;
  ownerEntityType?: string | null;
  isAbsentee?: boolean | null;
  tenureYears?: number | null;
  lastSalePrice?: number | null;
  lastSaleDate?: string | null;
  confidence?: "real" | "modeled";
}

export interface ResolvedRule { slug: string; condition: string; recommendation: string; source: string; }

const usd = (n: number | null | undefined) =>
  n == null ? "—" : `$${Math.round(n).toLocaleString()}`;
const pct = (x: number | null | undefined) =>
  x == null ? "—" : `${(x * 100).toFixed(1)}%`;

function proFormaBlock(label: string, pf: ScoreResult["proFormas"]["wholeHouse"] | undefined): string {
  if (!pf) return `**${label}:** not applicable.`;
  return `**${label}** — gross ${usd(pf.grossAnnualRent)}/yr · NOI ${usd(pf.noi)} · ` +
    `cap rate ${pct(pf.capRate)} · cash-on-cash ${pct(pf.cashOnCash)}`;
}

function offerBlock(o: Offer): string {
  const lines = [
    `### ${o.rank}. ${o.structure.replace(/_/g, " ")}${o.attorneyReviewRequired ? "  ⚠️ attorney review required" : ""}`,
    o.sellerPitch && `- **Seller pitch:** ${o.sellerPitch}`,
    o.capGains && `- **Cap-gains modeler:** seller defers ~${usd(o.capGains.sellerBenefit)} vs a cash sale (gain ${usd(o.capGains.estGain)}).`,
    `- **Nate:** cash in deal ${usd(o.buyer.cashInDeal)} — ${o.buyer.capitalEfficiency}`,
    o.legalGuardrail && `- **⚖️ Legal guardrail:** ${o.legalGuardrail}`,
    o.citedRules.length && `- **Cites:** ${o.citedRules.join(", ")}`,
  ].filter(Boolean);
  return lines.join("\n");
}

export function renderDossier(
  f: DossierFacts, score: ScoreResult, financing: FinancingResult, rules: ResolvedRule[],
  depth: DossierDepth = {},
): string {
  const h = score.headline;
  const modeled = f.confidence !== "real";
  const out: string[] = [];

  out.push(`# Deal Dossier — ${f.address}`);
  out.push(`*Generated by the LOT engine. **Score: ${score.score.toFixed(0)}/100.** ` +
    `Headline model: **${h.model.replace(/_/g, "-")}** at ${pct(h.proForma.cashOnCash)} cash-on-cash` +
    `${depth.dataConfidence != null ? ` · data confidence ${depth.dataConfidence.toFixed(2)}` : ""}.*`);
  if (depth.gates && !depth.gates.passed) {
    out.push(`\n> ⚠️ **Thesis constraint flag${depth.gates.failures.length > 1 ? "s" : ""}:** ` +
      `${depth.gates.failures.join("; ")}. ` +
      `Shown for your judgment (not hidden) — but it trips a thesis red-line, so verify before acting.`);
  } else if (depth.gates) {
    out.push(`\n> ✓ Passes all thesis hard-constraint gates.`);
  }
  out.push("");
  out.push(`**Data provenance:** ✅ REAL (county): zoning, assessed value, sale history, owner, coordinates. ` +
    `🟨 MODELED (flagged): bedroom rents${f.beds == null ? " and bed count" : ""} → so the pro-formas are estimates. ` +
    `_Informational, not legal or financial advice._`);
  if (score.lowConfidence) out.push(`\n> ⚠️ **Low confidence:** bed count is unknown, so the by-room model can't run and the pro-forma is a rough estimate. Verify beds (Residential Details) before acting.`);

  // Snapshot
  out.push(`\n## Snapshot (real)`);
  out.push(`| Field | Value |\n|---|---|`);
  out.push(`| Parcel # | ${f.apn}${f.gpin ? ` · GPIN ${f.gpin}` : ""} |`);
  out.push(`| Zone | ${f.zoneCode ?? "—"} |`);
  out.push(`| Assessed value | **${usd(f.assessedValue)}** |`);
  out.push(`| Beds | ${f.beds ?? "unknown (modeled)"} |`);
  if (f.lastSalePrice) out.push(`| Last arm's-length sale | ${usd(f.lastSalePrice)}${f.lastSaleDate ? ` (${f.lastSaleDate})` : ""} |`);
  if (f.ownerName) out.push(`| Owner | ${f.ownerName} (${f.ownerEntityType ?? "?"})${f.isAbsentee ? " · absentee" : ""} |`);

  // Occupancy legality
  out.push(`\n## Occupancy legality (the make-or-break check)`);
  const legal = f.byRoomLegal === true ? "**by-the-room renting is legal**"
    : f.byRoomLegal === false ? "**by-the-room is NOT legal** here"
    : "by-room legality is **unknown** — needs a per-parcel determination";
  out.push(`- Zone ${f.zoneCode ?? "?"} → ${legal}.`);
  if (f.stabilityFlag) out.push(`- ⚠️ **Stability flag:** ${f.stabilityFlag}`);

  // Underwriting
  out.push(`\n## Underwriting (modeled financials over the real assessed value; all-cash)`);
  out.push(proFormaBlock("By-the-room", score.proFormas.byRoom));
  out.push("");
  out.push(proFormaBlock("Whole-house", score.proFormas.wholeHouse));

  if (depth.sensitivity) {
    const s = depth.sensitivity;
    out.push(`\n**Sensitivity** — headline CoC ${pct(s.cocBase)} · **range ${pct(s.cocLow)}–${pct(s.cocHigh)}** ` +
      `across ±rent/±vacancy (the number isn't fragile — or it is, if the range is wide).`);
  }

  // HUD FMR real floor (004a): a free-government reality check on the MODELED whole-house rent.
  if (depth.rentFloor?.hudFmrMonthly != null) {
    const rf = depth.rentFloor;
    out.push(`\n**HUD FMR floor (real)** — ${rf.cbsaName} FY${rf.fmrYear}: **${usd(rf.hudFmrMonthly)}/mo** whole-house ` +
      `for ${f.beds ?? "?"} bed(s) (40th-pct gross rent; a defensible FLOOR, not the student headline). ` +
      (rf.belowFloor
        ? `⚠️ Our modeled whole-house rent sits **below** this real floor — the rent model looks low for this parcel; verify.`
        : `Our modeled rent clears it.`));
  }

  // Score breakdown
  out.push(`\n## Score breakdown (${score.score.toFixed(0)}/100, vs your thesis)`);
  out.push(`| Component | Weight | Contribution |\n|---|---|---|`);
  for (const [key, c] of Object.entries(score.components)) {
    out.push(`| ${key.replace(/_/g, " ")} | ${(c.weight * 100).toFixed(0)}% | ${c.weighted >= 0 ? "+" : ""}${c.weighted.toFixed(1)} |`);
  }

  // Financing
  out.push(`\n## Financing recommendation 💵`);
  for (const o of financing.recommended) out.push(offerBlock(o) + "\n");
  // assumptions are deal-level (same across offers) — print once, not per offer
  if (financing.recommended[0]) {
    out.push(`_Assumptions (deal-level):_ ${financing.recommended[0].assumptions.join("; ")}`);
  }
  if (financing.suppressed.length) {
    out.push(`**Suppressed structures** (the engine won't force creative finance where it doesn't fit):`);
    for (const s of financing.suppressed) out.push(`- **${s.structure.replace(/_/g, " ")}** — ${s.reason}`);
  }
  if (rules.length) {
    out.push(`\n### Cited rules (the "why", auditable)`);
    for (const r of rules) out.push(`- **${r.slug}** — ${r.recommendation} _(${r.source})_`);
  }

  // Verdict
  out.push(`\n## Verdict`);
  out.push(score.lowConfidence
    ? `**Needs data.** Pull real beds + rent comps before trusting these numbers.`
    : `Score **${score.score.toFixed(0)}/100**, headline ${pct(h.proForma.cashOnCash)} cash-on-cash via the ${h.model.replace(/_/g, "-")} model. ` +
      `Recommended financing: **${(financing.recommended[0]?.structure ?? "cash").replace(/_/g, " ")}**.`);
  out.push(modeled ? `\n_Beds/rents are modeled — verify before acting._` : "");

  return out.join("\n");
}
